### ISSUE TITLE
VS2015 can't load the package after last update

### ISSUE THREAD

**Issue by MartinL0815** [dogfuntom/ProjectColoredFrame#2]
Here the data from the "Activity Monitor Log":

- ``326 Begin package load [ProjectColoredFramePackage] {43FB5A60-1F34-4E15-9C4D-89B1F9087D67}  VisualStudio 2018/04/10 09:05:24.619``
- ``327 ERROR LegacySitePackage failed for package [ProjectColoredFramePackage]Source: 'ProjectColoredFrame' Description: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at ProjectColoredFrame.Mapping.ColorDecider.Map(Solution solution, IReadOnlyList`1 palette) at ProjectColoredFrame.Mapping.ColorDecider..ctor(Solution solution, SignatureGenerator signatureGenerator) in C:\Users\Maxim\Source\Repos\ProjectColoredFrame\ProjectColoredFrame\Mapping\ColorDecider.cs:line 37 at ProjectColoredFrame.Core.Services.Remap() in C:\Users\Maxim\Source\Repos\ProjectColoredFrame\ProjectColoredFrame\Core\Services.cs:line 34 at ProjectColoredFrame.Core.Services..ctor(DTE2 dte) in C:\Users\Maxim\Source\Repos\ProjectColoredFrame\ProjectColoredFrame\Core\Services.cs:line 26 at ProjectColoredFrame.ProjectColoredFramePackage.Initialize() in C:\Users\Maxim\Source\Repos\ProjectColoredFrame\ProjectColoredFrame\ProjectColoredFramePackage.cs:line 69 at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].  {43FB5A60-1F34-4E15-9C4D-89B1F9087D67} 80070002 VisualStudio 2018/04/10 09:05:24.667``
- ``328 ERROR SetSite failed for package [ProjectColoredFramePackage](null) {43FB5A60-1F34-4E15-9C4D-89B1F9087D67} 80070002 VisualStudio 2018/04/10 09:05:24.674``
- ``329 ERROR End package load [ProjectColoredFramePackage] {43FB5A60-1F34-4E15-9C4D-89B1F9087D67} 80070002 VisualStudio 2018/04/10 09:05:24.676``

**Comment by MartinL0815** [comment]
I have overseen another error entry before:

- ``235 ERROR Could not find a part of the path 'C:\USERS\LEMBURG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\CIFNROM4.ANQ\ProjectColoredFrame.dll'.
          C:\USERS\LEMBURG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\CIFNROM4.ANQ\ProjectColoredFrame.dll   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2018/04/10 09:05:07.500``

**Comment by MartinL0815** [comment]
Should I uninstall/re-install and what's about the settings after uninstalling and restarting VS2015?

**Comment by dogfuntom** [comment]
As far as I know VS don't remove settings of an extension when uninstalling it. Anyway, don't uninstall/reinstall it. It won't help.
I'm fixing it now and it should just work after I'll post an update with the fix.
